# enable_rgb = true
# import = ["/Users/mahadiahmed/.config/alacritty/themes/rose-pine.toml"]
import = ["/Users/mahadiahmed/.config/alacritty/themes/rose-pine-moon.toml"]
# import = ["/Users/mahadiahmed/.config/alacritty/themes/rose-pine-dawn.toml"]
# import = ["/Users/mahadiahmed/.config/alacritty/themes/gruvbox_dark.toml"]
# import = ["/Users/mahadiahmed/.config/alacritty/themes/gruvbox_light.toml"]
# import = ["/Users/mahadiahmed/.config/alacritty/themes/kanagawa.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 16.0
# style = "Beam"
# vi_mode_style = "Block"

[font.normal]
family = "FiraCode Nerd Font"

[window]
decorations = "buttonless"
dynamic_title = true
opacity = 0.95
startup_mode = "Windowed"

[window.padding]
x = 10
y = 10
