"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000

format = """

$os\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$nodejs\
$golang\
$ruby\
$lua\
$python\
$kotlin\
$line_break\
$character"""

right_format = """
$jobs\
$direnv\
$aws\
$cmd_duration\
$time"""

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[cmd_duration]
min_time = 500
format = '[ $duration]($style)'

[git_branch]
format = "[on]($style) [$symbol$branch ]($style)"

[git_status]
format = "([\\[$all_status$ahead_behind\\]]($style) )"
conflicted = "~"
ahead = "⇡"
behind = "⇣"
diverged = "⇣${ahead_count}⇡${behind_count}"
untracked = "?"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
stashed = "*"

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = true
style = 'bold blue'
symbol = " "


[time]
disabled = false
format = '[  $time ]($style)'


[nodejs]
symbol = ""
format = "[$symbol ($version )]($style)"

[golang]
symbol = ""
format = "[$symbol ($version )]($style)"

[ruby]
symbol = ""
format = "[$symbol ($version )]($style)"

[java]
symbol = " "
format = "[$symbol ($version )]($style)"

[python]
symbol = ""
format = "[$symbol ($version )]($style)"

[lua]
symbol = ""
format = "[$symbol ($version )]($style)"

[docker_context]
symbol = ""
format = "[$symbol ($context )]($style)"
